# Generated by Django 5.2.18 on 2026-10-08 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=80, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('passport_id', models.CharField(max_length=40, unique=True, verbose_name='Passport / ID')),
                ('birth_date', models.DateField(verbose_name='Tug‘ilgan sana')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=8, verbose_name='Jinsi')),
                ('citizenship', models.CharField(default='O‘zbekiston', max_length=80, verbose_name='Fuqaroligi')),
                ('address', models.CharField(max_length=240, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Mehmon',
                'verbose_name_plural': 'Mehmonlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Xona raqami')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qavat')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=12, verbose_name='Xona turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi (so‘m)')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sig‘imi')),
                ('status', models.CharField(choices=[('available', 'Bo‘sh'), ('occupied', 'Band'), ('maintenance', 'Ta’mirda'), ('cleaning', 'Tozalanmoqda')], default='available', max_length=16, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['number'],
            },
        ),
    ]
